# Generated by Django 4.0.3 on 2022-09-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeahChallenge',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='Challenge')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Problems', models.TextField(blank=True, null=True)),
                ('Negative', models.TextField(blank=True, null=True)),
                ('Solution', models.TextField(blank=True, null=True)),
                ('ProblemRepeat', models.TextField(blank=True, null=True)),
                ('Places', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeahContact',
            fields=[
                ('ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('PhoneNum', models.TextField(blank=True, max_length=200, null=True)),
                ('Address', models.TextField(blank=True, max_length=200, null=True)),
                ('startTime', models.TextField(blank=True, max_length=200, null=True)),
                ('EndTime', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeahFooter',
            fields=[
                ('ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('TwiterLink', models.URLField(blank=True, null=True)),
                ('LinkedinLink', models.URLField(blank=True, null=True)),
                ('InstagramLink', models.URLField(blank=True, null=True)),
                ('Conditions', models.TextField(blank=True, null=True)),
                ('Privacy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeahJoinConditions',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('condition', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='BeahPartener',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('URl', models.URLField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='Partener')),
            ],
        ),
        migrations.CreateModel(
            name='BeahProjects',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectDescription', models.TextField()),
                ('ProjectProposal', models.FileField(upload_to='Proposal')),
                ('projectLogo', models.ImageField(upload_to='projectsLogo')),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('ProjectProblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahchallenge')),
            ],
            options={
                'ordering': ['-publishDate'],
            },
        ),
        migrations.CreateModel(
            name='BeahPromotionalImages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TitleArabic', models.CharField(max_length=200)),
                ('TitleEnglish', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to='Promotional')),
            ],
        ),
        migrations.CreateModel(
            name='BeahSubjects',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100)),
                ('SubjectDescription', models.TextField()),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('SubjectStatus', models.IntegerField(choices=[(0, 'public'), (1, 'private')])),
                ('ProjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahprojects')),
            ],
        ),
        migrations.CreateModel(
            name='BeahTec',
            fields=[
                ('ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='BeahTec')),
            ],
        ),
        migrations.CreateModel(
            name='BeahTecCollege',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CollegeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BeahUsers',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(max_length=150)),
                ('UserType', models.IntegerField(choices=[(0, 'Admin'), (1, 'Team'), (2, 'Support')])),
            ],
        ),
        migrations.CreateModel(
            name='BeahVisitors',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserPassword', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeahTeam',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=100)),
                ('JoinDate', models.DateTimeField(auto_now_add=True)),
                ('MemberNum', models.CharField(max_length=100)),
                ('PhoneNum', models.CharField(max_length=100)),
                ('UserStatus', models.IntegerField(choices=[(0, 'Approved'), (1, 'Not Approved')])),
                ('CollegeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahteccollege')),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
            ],
        ),
        migrations.CreateModel(
            name='BeahSubjectsLike',
            fields=[
                ('LikeID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahsubjects')),
                ('UserID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
                ('visitorID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahvisitors')),
            ],
        ),
        migrations.CreateModel(
            name='BeahSubjectsImages',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectImage', models.ImageField(upload_to='Subjects')),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahsubjects')),
            ],
        ),
        migrations.CreateModel(
            name='BeahSubjectsComments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Comments', models.TextField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('SubjectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahsubjects')),
                ('UserID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
                ('visitorID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahvisitors')),
            ],
        ),
        migrations.CreateModel(
            name='BeahRandomCode',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('randomCode', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
                ('visitorID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahvisitors')),
            ],
        ),
        migrations.AddField(
            model_name='beahprojects',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahteam'),
        ),
        migrations.CreateModel(
            name='BeahNotifications',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=300)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('isSeen', models.BooleanField(default=False)),
                ('role', models.TextField(max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
            ],
            options={
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='BeahMember',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(max_length=100)),
                ('MemberMajor', models.CharField(max_length=100)),
                ('MemberDescription', models.TextField()),
                ('MemberImage', models.ImageField(upload_to='MemberImage')),
                ('MemberGender', models.CharField(max_length=20)),
                ('MemberStudyYear', models.CharField(max_length=50)),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahteam')),
            ],
        ),
        migrations.CreateModel(
            name='BeahArticles',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleTitle', models.CharField(max_length=200)),
                ('ArticleDescription', models.TextField()),
                ('ArticleImage', models.ImageField(upload_to='Articles')),
                ('ArticleStatus', models.IntegerField(choices=[(0, 'public'), (1, 'private')])),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
            ],
            options={
                'ordering': ['-CreatedDate'],
            },
        ),
    ]
