# Generated by Django 4.0.3 on 2022-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0003_beahsubjectslike_djangoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahrandomcode',
            name='IsActive',
            field=models.BooleanField(default=0),
        ),
    ]
