# Generated by Django 4.0.3 on 2022-09-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0004_beahrandomcode_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beahrandomcode',
            name='IsActive',
        ),
        migrations.AddField(
            model_name='beahvisitors',
            name='IsActive',
            field=models.BooleanField(default=0),
        ),
    ]
