# Generated by Django 4.0.3 on 2022-09-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0006_beahsubjectscomments_djangoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beaharticles',
            name='AdminID',
        ),
    ]
