# Generated by Django 4.1.2 on 2022-10-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0008_beahrandomcode_djangoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beahteam',
            name='CollegeName',
            field=models.CharField(max_length=100),
        ),
    ]
