# Generated by Django 4.1.2 on 2022-10-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0009_alter_beahteam_collegename'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahteam',
            name='CollegeOther',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='beahteam',
            name='CollegeName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahteccollege'),
        ),
    ]
