# Generated by Django 4.1.2 on 2022-10-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0010_beahteam_collegeother_alter_beahteam_collegename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beahteam',
            name='CollegeOther',
        ),
    ]
