# Generated by Django 4.1.2 on 2022-10-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0011_remove_beahteam_collegeother'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahteam',
            name='CollegeOther',
            field=models.CharField(default='', max_length=100),
        ),
    ]
