# Generated by Django 4.1.2 on 2022-10-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0013_remove_beahteam_collegeother'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeahTeamNew',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=100)),
                ('JoinDate', models.DateTimeField(auto_now_add=True)),
                ('MemberNum', models.CharField(max_length=100)),
                ('PhoneNum', models.CharField(max_length=100)),
                ('UserStatus', models.IntegerField(choices=[(0, 'Approved'), (1, 'Not Approved')])),
                ('CollegeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahteccollege')),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backapi.beahusers')),
            ],
        ),
    ]
