# Generated by Django 4.1.2 on 2022-10-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0014_beahteamnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahteccollege',
            name='Main',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='BeahTeamNew',
        ),
    ]
