# Generated by Django 4.1.2 on 2022-10-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0015_beahteccollege_main_delete_beahteamnew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beahteccollege',
            old_name='Main',
            new_name='Other',
        ),
    ]
