# Generated by Django 4.1.2 on 2022-10-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0016_rename_main_beahteccollege_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beahteccollege',
            name='Other',
        ),
    ]
