# Generated by Django 4.1.2 on 2022-10-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0017_remove_beahteccollege_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahteccollege',
            name='Other',
            field=models.BooleanField(default=True),
        ),
    ]
