# Generated by Django 4.1.2 on 2022-10-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0018_beahteccollege_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beahteccollege',
            old_name='Other',
            new_name='Main',
        ),
    ]
