# Generated by Django 4.1.2 on 2022-10-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0020_alter_beaharticles_articleimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beaharticles',
            name='ArticleImage',
            field=models.ImageField(upload_to='Articles'),
        ),
        migrations.AlterField(
            model_name='beahmember',
            name='MemberImage',
            field=models.ImageField(upload_to='MemberImage'),
        ),
        migrations.AlterField(
            model_name='beahprojects',
            name='ProjectProposal',
            field=models.FileField(upload_to='Proposal'),
        ),
        migrations.AlterField(
            model_name='beahprojects',
            name='projectLogo',
            field=models.ImageField(upload_to='projectsLogo'),
        ),
        migrations.AlterField(
            model_name='beahpromotionalimages',
            name='Image',
            field=models.ImageField(upload_to='Promotional'),
        ),
        migrations.AlterField(
            model_name='beahsubjectsimages',
            name='SubjectImage',
            field=models.ImageField(upload_to='Subjects'),
        ),
        migrations.AlterField(
            model_name='beahtec',
            name='Image',
            field=models.ImageField(upload_to='BeahTec'),
        ),
    ]
