# Generated by Django 4.1.2 on 2022-10-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0022_beahprojects_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahchallenge',
            name='SubDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beahchallenge',
            name='SubTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beahchallenge',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
