# Generated by Django 4.1.2 on 2022-10-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0023_beahchallenge_subdescription_beahchallenge_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahteam',
            name='selected',
            field=models.IntegerField(default=0),
        ),
    ]
