# Generated by Django 4.1.2 on 2022-11-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0025_alter_beahusers_userpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beahprojects',
            name='ProjectName',
            field=models.CharField(max_length=300),
        ),
    ]
