# Generated by Django 4.1.2 on 2023-01-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0026_alter_beahprojects_projectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='beahmember',
            name='TeamLogo',
            field=models.ImageField(default=None, null=True, upload_to='TeamsLogo'),
        ),
    ]
