# Generated by Django 4.1.2 on 2023-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0027_beahmember_teamlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beahmember',
            name='TeamLogo',
        ),
        migrations.AddField(
            model_name='beahteam',
            name='TeamLogo',
            field=models.ImageField(default=None, null=True, upload_to='TeamsLogo'),
        ),
    ]
