# Generated by Django 4.1.2 on 2023-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0028_remove_beahmember_teamlogo_beahteam_teamlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beahsubjects',
            name='SubjectName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
