# Generated by Django 4.1.2 on 2023-02-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backapi', '0029_alter_beahsubjects_subjectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeahTeamVote',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.TextField(max_length=8)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('TeamID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backapi.beahteam')),
            ],
        ),
    ]
