from django.urls import path
from .import views
urlpatterns = [
    path('/info/', views.join, name='join'),
    path('/login/', views.login, name='login'),
    path('/teams/', views.teams, name='teams'),
    path('/updatestatus/', views.teamsStatusUpdate, name='updatestatus'),
    path('/addArticles/', views.addArticles, name='createarticle'),
    path('/articles/', views.displayArticles, name='displayarticle'),
    path('/articles/<int:id>/', views.articlesDetails, name='detailsarticle'),
    path('/articlesupdate/', views.articleUpdate, name='articleUpdate'),
    path('/articleinweb/', views.display4Articles, name='display4Articles'),
    path('/contact/', views.Contact, name='Contact'),
    path('/delete/', views.deleteArticle, name='Delete'),
    path('/project/<str:email>/', views.projectDetails, name='prodetails'),
    path('/projectUpdate/', views.projecteUpdate, name='proUpdate'),
    path('/addSubject/', views.addSubject, name='subadd'),
    path('/deleteSubject/', views.deleteSubject, name='deleteSub'),
    path('/SubjectDetails/<int:SID>/<int:PID>/',
         views.SubjectDetails, name='subdetails'),
    path('/deleteImage/', views.deleteImageSubject, name='deleteimage'),
    path('/subjectupdate/', views.SubjectUpdate, name='subupdate'),
    path('/team/<str:email>/', views.teamDetails, name='teamDetails'),
    path('/phone/', views.TeamPhoneNumUpdate, name='phoneUpdate'),
    path('/member/', views.TeamMemberNumUpdate, name='TeamMemberNumUpdate'),
    path('/addMember/', views.addMember, name='addMember'),
    path('/deletemember/', views.deleteMember, name='deleteMember'),
    path('/MemberDetails/<int:MID>/<int:TID>/',
         views.MemberDetails, name='memdetails'),
    path('/memberupdate/', views.MemberUpdate, name='MemberUpdate'),
    path('/project4/', views.Projects, name='ProjectsOnSlider'),
    path('/projectDetails/<int:id>/', views.ProjectsDetails, name='ProjectDetails'),
    path('/subjectPage/<int:pid>/<int:tid>/<int:sid>',
         views.SubjectDetailsPage, name='SubjectDetailsPage'),
    path('/projectsInAdmin/', views.DisplayProjectInAdmin,
         name='DisplayProjectInAdmin'),
    path('/projectsDetailsAdmin/<int:pid>',
         views.ProjectDetailsAdmin, name='ProjectDetailsAdmin'),
    path('/messageAll/', views.EmailToAllParticipate,
         name='EmailToAllParticipate'),
    path('/addcomments/', views.addComments,
         name='addComments'),
    path('/privilege/', views.CheckPrivilege,
         name='CheckPrivilege'),
    path('/deleteComment/', views.deleteComments,
         name='deleteComments'),
    path('/Like/', views.LikeButton,
         name='LikeButton'),
    path('/footer/', views.FooterDisplay,
         name='footerdisplay'),
    path('/footerupdate/', views.FooterUpdate,
         name='FooterUpdate'),
    path('/addpartener/', views.addPartener,
         name='addPartener'),
    path('/parteners/', views.displayPartener,
         name='displayPartener'),
    path('/deleteparteners/', views.deletePartener,
         name='deletePartener'),
    path('/partenersdetails/<int:id>', views.PartenersDetails,
         name='PartenersDetails'),
    path('/partenerupdate/', views.PartenerUpdate,
         name='PartenerUpdate'),
    path('/displaychallenges/', views.displayChallenges,
         name='displayChallenges'),
    path('/addChallenge/', views.addChallenge,
         name='addChallenge'),
    path('/deleteChallenge/', views.deleteChallenge,
         name='deleteChallenge'),
    path('/challengedetails/<int:id>', views.challengeDetails,
         name='challengedetails'),
    path('/challengeupdate/', views.challengeUpdate,
         name='challengeupdate'),
    path('/beahtecupdate/', views.BeahTecUpdate,
         name='BeahTecUpdate'),
    path('/beahTecdisplay/', views.BeahTecDisplay,
         name='BeahTecDisplay'),
    path('/addPromotional/', views.addPromotionalImages,
         name='addPromotionalImages'),

    path('/displayPromotional/', views.displayPromotionalImages,
         name='displayPromotionalImages'),
    path('/addcollege/', views.addCollege,
         name='addCollege'),
    path('/displaycolleges/', views.displayColleges,
         name='displayColleges'),
    path('/deletecollege/', views.deleteCollege,
         name='deleteCollege'),
    path('/collegedetails/<int:id>', views.CollegeDetails,
         name='CollegeDetails'),
    path('/collegeupdate/', views.CollegeUpdate,
         name='Collegeupdate'),
    path('/collegesandchallenges/', views.DisplayColleges_Challenges,
         name='collegeChallenges'),
    path('/contactupdate/', views.ContactUpdate,
         name='ContactUpdate'),
    path('/displaycontact/', views.ContactDisplay,
         name='ContactDisplay'),
    path('/displayfootercontact/', views.Footer_ContactDisplay,
         name='FooterContactDisplay'),
    path('/useradmin/', views.addAdmin,
         name='addAdmin'),
    path('/displayAdmin/<str:email>', views.DisplayAdmin,
         name='DisplayAdmin'),
    path('/deleteadmin/', views.deleteAdmin,
         name='deleteAdmin'),
    path('/admindetails/<int:id>', views.AdminDetails,
         name='AdminDetails'),
    path('/adminupdate/', views.AdminUpdate,
         name='AdminUpdate'),
    path('/statisticsONSite/', views.statisticsONSite,
         name='statisticsONSite'),
    path('/adminNotifications/', views.DisplayIsSeenAdminNotifications,
         name='DisplayAdminNotifications'),
    path('/joinconditions/', views.addJoinCondition,
         name='addJoinCondition'),
    path('/deleteconditions/', views.deleteJoinCondition,
         name='deleteJoinCondition'),
    path('/updateconditions/', views.JoinConditionUpdate,
         name='updateJoinCondition'),
    path('/updatenotify/', views.UpdateAdminNotifications,
         name='UpdateAdminNotifications'),
    path('/AllNotifications/', views.AllAdminNotifications,
         name='AllAdminNotifications'),
    path('/sendnotifications/', views.SendNotification4Team,
         name='SendNotification4Team'),
    path('/teamnotify/<str:email>/', views.TeamNotifyISSeen, name='tnotify'),
    path('/allteamnotify/<str:email>/',
         views.AllteamNotifications, name='alltnotify'),
    path('/checkemail/',
         views.checkIfEmailExit, name='checkemail'),
    path('/resendcode/',
         views.ResendCode, name='ResendCode'),
    path('/checkcode/',
         views.checkCorrectCode, name='checkCorrectCode'),
    path('/resetpassword/',
         views.ResetPassword, name='ResetPassword'),
    path('/regEmail/',
         views.visitorRegister, name='visitorRegister'),
    path('/renewCode/', views.ResendCodetovisitor, name='ResendCodetovisitor'),
    path('/checkVisitorCode/',
         views.checkCorrectVisitorCode, name='checkCorrectVisitorCode'),
    path('/checkLike/',
         views.checkUserMakeLike, name='checkUserMakeLike'),
     path('/adminstatistics/',
         views.adminStatistics, name='adminStatistics'),
     path('/djangoUser/',
         views.getUserfromDjango, name='getUserfromDjango'),
     path('/checkSadmin/<str:email>',
         views.checkSuperAdmin, name='checkSuperAdmin'),

]

